### ISSUE TITLE
Adding support for lg Sj8000

### ISSUE THREAD

**Issue by jwtiyar** [PredatH0r/ChanSort#190] opened 2020-09-23 09:23 UTC
Hey Can you add support to LG sJ series please?
[TTL](https://drive.google.com/file/d/1rEjBxgjInAdbYSwnRKdcVXvEIz6rfXOp/view?usp=sharing)

**Comment by PredatH0r** [comment] 2020-11-20 23:44
The format of your file (Global Clone version 100.000) is already supported by ChanSort.
When I open the file I see 186 DTV channels, 10 digital radio channels, 148 satellite TV channels and 15 satellite radio channels.
Do you experience any issues opening this file or later when importing the file back in the TV?

**Comment by jwtiyar** [comment] 2020-11-25 09:57
> The format of your file (Global Clone version 100.000) is already supported by ChanSort.
> When I open the file I see 186 DTV channels, 10 digital radio channels, 148 satellite TV channels and 15 satellite radio channels.
> Do you experience any issues opening this file or later when importing the file back in the TV?

Yes right
Is there any channel list to add?

**Comment by PredatH0r** [comment] 2021-07-27 10:46
closing because it is unclear what the problem is (loging into ChanSort, or loading the modified filed back into the TV)

**Closed by PredatH0r** 2021-07-27 10:46 UTC
