### ISSUE TITLE
Sony KD-55XH9005 - checksum error / NullReference

### ISSUE THREAD

**Issue by astroni** [PredatH0r/ChanSort#208] opened 2020-12-13 08:04 UTC
I'm unable to load the sdb.xml file.
first I get a checksum error and if I change the checksum manually to the expected one, then an error is raising:
System.NullReferenceExecption ... ChanSort.Ui.ReferenceListFromSetInput(SerializerBaseser) ... ChanSort.Ui.ReferenceListForm.<OnLoad>b__6_0()

**Comment by PredatH0r** [comment] 2020-12-13 12:41
Can you please send me your file (.xml and .bak) so I can take a look?
Was that file fresh from the TV or was it edited with ChanSort or another editor before?

**Comment by BadIDMan** [comment] 2021-02-08 19:29
The same issue.
ChanSort.Loader.Sony.dll (Sony (sdb.xml)): Invalid checksum: expected 0x9fdea9de, calculated 0x5d86cebe

Steps to reproduce:
1. Export channels list in Sony TV -> exported file is sdb.xml
2. Use Sony Channel Editor (https://www.sony.co.uk/electronics/support/downloads/00016025) and sort channels -> save the file as sdb-new.xml
3. Try to open sdb-new.xml file with ChanSort -> error as above.
4. When checksum at the end of the file in section <CheckSum></CheckSum> is replaced by calculated checksum then file can be open.

**Comment by PredatH0r** [comment] 2021-02-08 20:17
Can you please upload / send me your sdb.xml file please?
Sony has several different file format versions at and all the test files I currently have load fine.

**Comment by BadIDMan** [comment] 2021-02-08 20:47
Yes, it is possible to open sdb.xml file generated by Sony TV but can't be open when it is edited by Sony Channel Editor.
PS. Files already sent to you.
Good luck in troubleshooting.

**Comment by PredatH0r** [comment] 2021-02-09 08:17
Unfortunately I did not receive any files. My email address is horst@beham.biz.
If the TV's original file can be opened with ChanSort, but a file modified with the Sony Editor cannot because of a bad checksum, then it's most likely a problem in the Sony Editor that writes wrong checksums.

You can try and import the Sony-Editor modified list in your TV. If the checksum is really wrong, the TV will reject it.
You can also try to edit your original TV's export with ChanSort only and import it back to the TV. If it accepts it, ChanSort does calculate the checksums correctly.

**Comment by PredatH0r** [comment] 2021-02-09 15:04
The problem is now fixed in this update: https://github.com/PredatH0r/ChanSort/releases/tag/v2021-02-09

**Closed** 2021-07-27 10:14 UTC
