### ISSUE TITLE
Philips format version 125

### ISSUE THREAD

**Issue by emurekanu** [PredatH0r/ChanSort#424] opened 2024-09-29 18:40 UTC
![Ekran görüntüsü 2024-09-29 213935](https://github.com/user-attachments/assets/d87328a4-2f91-4ad3-ad7b-c740b2f03a4c)
When will we get support for version 125?

**Comment by emurekanu** [comment] 2024-09-29 18:42
[Uploading PhilipsChannelMaps.zip…]()

**Comment by emurekanu** [comment] 2024-09-29 18:42
[PhilipsChannelMaps.zip](https://github.com/user-attachments/files/17180766/PhilipsChannelMaps.zip)

**Comment by emurekanu** [comment] 2024-09-30 01:21
Device name 
Philips 55OLED908/12

**Comment by PredatH0r** [comment] 2024-09-30 10:59
What version of ChanSort did you use? (you can find it in the title bar of the ChanSort window)
I uploaded an experimental version to https://chansort.com/ChanSort_2024-09-30.zip which SHOULD support editing the favorites list.
This version DOES NOT support changing the main program numbers. (It won't prevent you from doing so, but it will only update the DVB*.xml files and not the MtkChannelList.xml file which is new to Philips formats 120 and 125).

I'm trying to get full support for editing the main list too, but that is work-in-progess and there are some open questions that I need answers for.

**Comment by PredatH0r** [comment] 2024-09-30 12:44
I dont't get any warnings/error when I open the DVBSall.xml you uploaded yesterday.
Did you run a new channel search after you posted the file?
A bad checksum can be caused by serveral reasons, including bad USB-stick, inconsistent data exported by the TV or a manual edit of any of the DVB*.xml files (which then no longer matches the checksums stored in chanLst.bin)
If you made manual edits you can click on "Ignore the error".
Please only change the favorite lists, not the main channel numbers. 

Editing of MtkChannelList.xml is experimental work-in-progress at the moment. 
It only edits that file in isolation without making the same adjustments to the DVB*.xml files. There is no checksum for this file, so there won't be any warning when opening it.

I assume that the TV expects the data in MtkChannelList.xml and DVBSall.xml to be consistent and I haven't had time yet to synchronize changes between the lists. That's what I am currently working on.

**Comment by emurekanu** [comment] 2024-09-30 13:04
I copy to usb channels again. This time DVBSall.xml opened when i try to copy the channels from MtkChannelList.xml and try to save this happens 
![Ekran görüntüsü 2024-09-30 160306](https://github.com/user-attachments/assets/139d62b8-f300-4681-979b-c5467c068aea)
![Ekran görüntüsü 2024-09-30 160336](https://github.com/user-attachments/assets/7580e6b8-a725-4af5-b774-1c684054f49b)
![Ekran görüntüsü 2024-09-30 160345](https://github.com/user-attachments/assets/069a36f8-9a18-4b82-b404-2f68e1c5335e)

**Comment by emurekanu** [comment] 2024-09-30 13:16
I get same error for favorites

**Comment by PredatH0r** [comment] 2024-09-30 13:19
I just uploaded a new version, same link as above: https://chansort.com/ChanSort_2024-09-30.zip
The previous version was missing the \[Map125\] section in ChanSort.Loader.Philips.ini
Thanks a lot for your testing!

**Comment by emurekanu** [comment] 2024-09-30 13:23
> I just uploaded a new version, same link as above: https://chansort.com/ChanSort_2024-09-30.zip The previous version was missing the [Map125] section in ChanSort.Loader.Philips.ini Thanks a lot for your testing!

![image](https://github.com/user-attachments/assets/41ca2544-9190-4462-9fcf-6eee4d60967c)
in new version when i open DVBSall.xml or Favorite.xml it opens fine. But when i try to save getting this error what am i doing wrong?

**Comment by emurekanu** [comment] 2024-09-30 13:27
Okay re-downloaded the new version from link this time i could succesfully save the reference list let me try on tv if its working

**Comment by emurekanu** [comment] 2024-09-30 13:43
Changing favorites working on tv thanks for your effort :)

**Comment by PredatH0r** [comment] 2024-09-30 13:45
Great! Thanks for your feedback.
Some people mentioned that with ChannelMap_120, after some time (and maybe power off/on) the TV changed the list again on its own.
Please let me know if/when anything with your list goes wrong.

**Comment by emurekanu** [comment] 2024-09-30 14:05
Okay i will let you know if something goes wrong

**Comment by PredatH0r** [comment] 2024-10-01 08:25
Released as https://github.com/PredatH0r/ChanSort/releases/tag/v2024-10-01

**Closed by PredatH0r** 2024-10-01 08:25 UTC
