### ISSUE TITLE
Please make this wonderfull editor support TCL Google TV.

### ISSUE THREAD

**Issue by tomxhachijuroku** [PredatH0r/ChanSort#338] opened 2022-12-30 20:22 UTC
Please, here is my .tar channel list, for example:
[Channel_List_V8-R51MT05-LF1V460_20221223.zip](https://github.com/PredatH0r/ChanSort/files/10326171/Channel_List_V8-R51MT05-LF1V460_20221223.zip)

**Comment by Double-A-92** [comment] 2023-01-02 14:32
The data itself is stored in simple SQLite databases... **BUT** there is a CRC check, so it's probably not possible to edit it. Unless somebody can guess how that CRC is calculated exactly.

**Comment by PredatH0r** [comment] 2023-01-02 17:07
I used Hex Editor Neo to auto-calculate all sorts of checksums of DtvData.db and it appears that its CRC16-CCITT can be found in cloneCRC.bin at offset 2 (in little-endian byte order).
The CRC16-CCITT of satellite.db is stored at offset 4.
Everything else in the cloneCRC.bin has value 0.

So that particular problem is solved, the more severe is to find the time. 
I must get some business work done first and hope to do some work on ChanSort later this week.

**Comment by PredatH0r** [comment] 2023-01-03 10:33
@tomxhachijuroku What is the exact directory and name of the file that the TV writes to the USB stick?
Does it write a .tar file directly into the root folder or does it create a folder "Channel_List_V8-R51MT05-LF1V460_20221223" and inside a file named "Channel_List_V8-R51MT05-LF1V460_20221223.tar" or does it create a .zip file that contains the folder and the .tar?

**Comment by PredatH0r** [comment] 2023-01-03 18:27
@tomxhachijuroku 
Can you please give this version a try at let me know if it works?
https://github.com/PredatH0r/ChanSort/releases/tag/v2023-01-03

**Comment by matepor464** [comment] 2023-01-06 13:37
I successfully edited my channel list with 2023-01-04 version, but can't import it into the TV. While comparing the edited and original list in SQL lite 3 browser, i found that all the channel names went from "BLOB" (original) into their actual names, eg. "HBO HD" (edited). Maybe this is preventing a successful import?
If You find some time, please look into this issue - the official TCL channel editor has been down for some time now.

And to answer Your question from 3 days ago - TV writes the channel list to USB stick root directory as .tar file. The .tar file contains "database" folder with cloneCRC.bin file and another folder, "userdata", which in turn contains DtvData.db and satellite.db files

**Comment by PredatH0r** [comment] 2023-01-06 13:42
Thanks for the feedback, I'm looking into it right now

**Comment by PredatH0r** [comment] 2023-01-06 13:51
When I open your DtvData.db file with SQLiteStudio 3.2.1 it shows that in PrograminfoTbl table the ServiceName column has (default) data type VARCHAR(64).
I'm reading it as as string and stripping the trailing spaces.
I'm writing it also as a string without any further manipulation.

SQLite unfortunately can be very weird, allowing individual rows/fields have a different data type as the column's definition.
And Microsoft's .NET System.Data.Sqlite library has its own set of quirks to deal with this.
Where did you see that the name is a BLOB?

**Comment by matepor464** [comment] 2023-01-06 14:22
I see that You already found the BLOBs, but I will post screenshots anyway, in case it helps :)
I am using DB Browser for SQL Lite. "original.png" shows the original channel list. There are a lot more values displayed in binary for Channel 1.
After opening it with ChanSort and simply saving it, there are less values, and the name is shown (TVN HD), as seen on "edited.png"

I also want to mention that I know nothing about SQL lite, so my findings may be of little use to You.

**Comment by matepor464** [comment] 2023-01-06 14:28
![original](https://user-images.githubusercontent.com/122100836/211031713-7c6c5975-91fc-46fc-b400-a309834ffd7b.png)
![edited](https://user-images.githubusercontent.com/122100836/211031749-e77b0f37-84ab-48ba-b969-63a74069b277.png)
Forgot to attach files

**Comment by PredatH0r** [comment] 2023-01-06 14:29
https://github.com/PredatH0r/ChanSort/releases/tag/v2023-01-06 has now a new .zip that writes the names back as BLOB with length 64.
Let's hope that works :)

**Comment by matepor464** [comment] 2023-01-06 14:30
Thank You, I will try it out and let You know if everything works fine :)

**Comment by matepor464** [comment] 2023-01-06 15:25
Unfortunately it still does not work, but I have no further ideas as to why :( All the data in PrograminfoTbl table seem identical to the original file. Maybe the issue is in a different table or in cloneCRC file?
The edited file (only opening and saving) has 1 less kB in size, so this might indicate that some changes are made even just by saving, but it is only a wild guess.
Still, thank You for a quick response and an attempt at fixing the issue :)

**Comment by PredatH0r** [comment] 2023-01-06 16:25
In this new build here I removed the "REINDEX" statement that I usually execute on SQLite databases because it can help recover broken databases (which some TVs export).
The file size however is still 1KB less compared to the original file.

I'm not updating any other tables than PrograminfoTbl.
I do update the cloneCRC.bin file with the new checksum of DtvData.db. Reopening the saved file then verifies the CRC correctly.

Another possible cause is the library used to create the .tar. From what I've read there are several different flavors of .tar and the TV might only work with a specific one.
Opening the original one with 7zip and File / Properties it shows "Characteristics: GNU ASCII"
The saved one shows only "ASCII".
I have to try and find out if there is any way for me to control what TAR-dialect is used by the library.

Do you have a way to untar and re-tar the file modified with ChanSort and see if the TV can process it then?

![image](https://user-images.githubusercontent.com/6238104/211053893-46351812-06f8-41e9-985e-599f39abfa36.png)

**Comment by matepor464** [comment] 2023-01-06 16:40
I will try to re-tar it, but i have yet to find a way to do it. 
I used winRar to untar it and check .db files, but winRar can't tar them again

**Comment by matepor464** [comment] 2023-01-06 16:55
Just one question - how do You view the .tar file properties? I can't seem to find any info about GNU-ASCII/ASCII characteristics on Windows 11

**Comment by PredatH0r** [comment] 2023-01-06 16:57
I opened the .tar with 7zip and clicked on "File / Properties" menu within 7zip.

**Comment by matepor464** [comment] 2023-01-06 17:09
I extracted the original list with winRar, then used these commands to re-tar it:
![re-tar](https://user-images.githubusercontent.com/122100836/211061952-62d57b95-0838-4865-bf48-2d1ee7bb0792.png)

The TV accepted the .tar file, so I will be trying to edit the extracted files with ChanSort and then making a .tar file with cvf command

**Comment by matepor464** [comment] 2023-01-06 17:14
Didn't work with edited files :/ when I extracted the original files and then re-tarred them immediately it worked fine

**Comment by matepor464** [comment] 2023-01-06 17:21
One thing is strange - both unedited and edited .tar files are POSIX ASCII after I used cvf command, but only unedited file got accepted by the TV.

**Comment by PredatH0r** [comment] 2023-01-06 17:26
Maybe the problem isn't related to the .tar archiving after all.
I'll upload a new build that doesn't "REINDEX" the database and doesn't change the names or anything other than the ProgNum values. I hope that narrows down the cause.

**Comment by matepor464** [comment] 2023-01-06 17:55
So this is weird - simply copying the .tar file in Windows makes ot unable to be imported into the TV. 
I dont't know if You can do anything about that, maybe it is meant to be edited on another OS ;P

**Comment by PredatH0r** [comment] 2023-01-06 18:01
How did you perform the earlier test with un-taring and then re-taring? 
Was that under Windows or Linux and directly on the USB or copy to PC first and then back?
Also, did you use a FAT32 or NTFS formatted stick? TVs very often have issues with NTFS sticks or sticks >16GB.

It seems unlikely that simply copying back+forth causes the issue. But I'm at a point where I'm not ruling out anything anymore :)
So your last test was export from TV, copy to Windows and then straight back to USB and TV?

**Comment by matepor464** [comment] 2023-01-06 18:10
Last test was TV -> USB -> PC, then copying, and back to USB -> TV.
When re-taring, I copied the file to PC, extracted with winrar, then re-tarred with commands, copied to USB and then to TV
USB stick is FAT32.
I will try to make some tests again later and try to see what works and what doesn't.
The other thing is that TCL firmwares are famously bad, so it may be my TV's issue :)

**Comment by PredatH0r** [comment] 2023-01-06 18:22
I just created a new build using Win10's built-in "tar" command instead of the "SharpCompress" code library.
The "SharpCompress" library produced a .tar that just showed "ASCII" in 7-Zip.
The original is "GNU ASCII".
And the new build with Win10's tar shows "POSIX ASCII".

The original GNU version includes file permissions, user, group and group-id, while the others don't. 
Maybe the TV needs that data for the import. But then again, the untar-retar should not have worked either.

![image](https://user-images.githubusercontent.com/6238104/211073320-fde79013-5302-4052-8e73-b21058d13079.png)

I just uploaded my new Win10-tar based build here: https://chansort.com/ChanSort_2023-01-06_1920.zip

**Comment by matepor464** [comment] 2023-01-06 19:31
I no longer know what's going on. Just now I copied the original file 2 times, extracted them and then re-tarred it with 7-zip and cvf command on my PC - all 3 files could be imported into the TV.
Then I tried to use ChanSort on all of them and also on extracted original files which I then re-tarred as mentioned above - they couldn't be imported :( 
What is weird is that simply copying the file sometimes makes it unable to be imported. That was the first thing I tried - the copy of the original .tar couldn't be imported
But the again - the files which I re-tarred were also copies and they could be imported. I will try to ask TCL support about exporting channel lists and also send them the files - maybe they can tell what's wrong with the edited lists

**Comment by tomxhachijuroku** [comment] 2023-01-07 21:20
> I just created a new build using Win10's built-in "tar" command instead of the "SharpCompress" code library. The "SharpCompress" library produced a .tar that just showed "ASCII" in 7-Zip. The original is "GNU ASCII". And the new build with Win10's tar shows "POSIX ASCII".
> 
> The original GNU version includes file permissions, user, group and group-id, while the others don't. Maybe the TV needs that data for the import. But then again, the untar-retar should not have worked either.
> 
> ![image](https://user-images.githubusercontent.com/6238104/211073320-fde79013-5302-4052-8e73-b21058d13079.png)
> 
> I just uploaded my new Win10-tar based build here: https://chansort.com/ChanSort_2023-01-06_1925.zip EDIT: fixed link

Thank You Everyone!!!
It works fine with my TCL 43P638 Google TV, editing and importing 100%.
That's a big help since my TV provider likes to add and delete channels all the time with out notice and sorting over 120 channels with the remote was taking hours, thank you again and Happy new year!!!

**Comment by PredatH0r** [comment] 2023-01-07 21:26
oh wow, thanks for the feedback!
I am currently working on my own implementation to create "tar" archives because non of the windows implementations preserve file permissions and ownership and I thought that might have been the cause of matepor464's problems.
But good to know there is a was to get it actually working.

It would be great if you could give my final code another test once it is finished (probably tomorrow). I'll keep you posted.

**Comment by PredatH0r** [comment] 2023-01-08 00:54
latest build is now on https://chansort.com/ChanSort_2023-01-08.zip

It also allows changing names and set "hidden" and "favorites" flags, which was disabled in the 2023-01-06_1925 build.

**Comment by PredatH0r** [comment] 2023-01-08 09:29
latest build is now on https://chansort.com/ChanSort_2023-01-08.zip

It also allows changing names and set "hidden" and "favorites" flags, which was disabled in the 2023-01-06_1925 build.

**Comment by matepor464** [comment] 2023-01-08 11:57
> > I just created a new build using Win10's built-in "tar" command instead of the "SharpCompress" code library. The "SharpCompress" library produced a .tar that just showed "ASCII" in 7-Zip. The original is "GNU ASCII". And the new build with Win10's tar shows "POSIX ASCII".
> > The original GNU version includes file permissions, user, group and group-id, while the others don't. Maybe the TV needs that data for the import. But then again, the untar-retar should not have worked either.
> > ![image](https://user-images.githubusercontent.com/6238104/211073320-fde79013-5302-4052-8e73-b21058d13079.png)
> > I just uploaded my new Win10-tar based build here: https://chansort.com/ChanSort_2023-01-06_1925.zip EDIT: fixed link
> 
> Thank You Everyone!!! It works fine with my TCL 43P638 Google TV, editing and importing 100%. That's a big help since my TV provider likes to add and delete channels, all the time without notice and sorting over 120 HD channels with the remote was taking hours (They deleted all over 60 analog channels so it's less work but still), thank you again and Happy new year!!!

Could You describe Your exporting and importing process step by step? I have a 65C635 Google TV, so it should also work for me, but my TV doesn't accept the edited files. 
Which version of ChanSort did You use? Did You edit the .tar file directly, or did You extract it first?

**Comment by matepor464** [comment] 2023-01-10 12:32
I'm still trying to make it work somehow, tomxhachijuroku could import the file so it's highly possible that there is an issue on my end 😄. Thank you for trying to help me.
Anyway, I found a bug unrelated to my importing problems - when I use the empty list option while opening the .tar file, add some channels and want the rest deleted during saving I get this error: (build 2021-01-08)
![ChanSort delete error](https://user-images.githubusercontent.com/122100836/211551506-964b2867-79c8-48f2-a681-0413d083bc5c.png)
Adding the unsorted channels at the end of the list works fine, but I think that deleting them may be beneficial for the TV. I don't know exactly how EPG works in TVs, but maybe with less channels it could load faster?

**Comment by PredatH0r** [comment] 2023-01-10 14:43
Deleting is now fixed here: https://github.com/PredatH0r/ChanSort/releases/tag/v2023-01-10

Have you tried resetting your TV to factory defaults yet?
Some other TVs (e.g. LG WebOS 6) only import correctly on a freshly reset TV without any channels in its memory.
Reset is also sometimes needed when there was a firmware-update (maybe automatically) without re-scanning the channels later.
Since most TV manufacturers don't offer any editing software, the export/import function is mostly intended to fully clone one TV onto another identical one without having to scan channels there. Typical use-case for that are hotels with many identical TVs.

**Comment by matepor464** [comment] 2023-01-10 14:47
Haven't tried that yet, but definitely will, thanks for the advice. I did recently update the firmware, so maybe that's the problem

**Comment by PredatH0r** [comment] 2023-01-10 14:50
There is a "DatabaseInfoTbl" table inside DtvData.db which holds a u8Version value. 
Maybe the new firmware is now expecting a different value and rejects a list that was exported with an older firmware.

**Comment by Gp0n5** [comment] 2023-01-11 20:55
Hello, i have 55c728. edited and trying to import TV but it has error when importing. Using 2023-01-10 version.

**Comment by Gp0n5** [comment] 2023-01-11 21:20
> There is a "DatabaseInfoTbl" table inside DtvData.db which holds a u8Version value. Maybe the new firmware is now expecting a different value and rejects a list that was exported with an older firmware and version number in it.

I compared v470 and v474 exported files. Table values are same.

**Comment by PredatH0r** [comment] 2023-01-11 21:41
Thanks for sharing your findings.

I compared files from a 43P638 and a 65C635 that were sent to me.
While the user with the 43P638 said that the upload worked, two users with a 65C635 reported that it didn't work for them.
The databases of both models have identical structure and value 45 int DatabaseInfoTbl.u8Version.
I even used a hex editor to compare the modified and original DtvData.db. Except from the channel number and a few changed bytes in internal Sqlite data, they were identical. 
And the same with the .tar file after writing my own Tar library which keeps everything identical except checksum and the file size information.
It almost looks like that there is something wrong in the TV's firmware.

Did you use the TCL web-based editor before? I wonder if that editor worked for all models, or if they pulled the plug because it only worked for some models.

**Comment by Gp0n5** [comment] 2023-01-11 21:49
Yes, I used it before. But link not works for a while. Because of that I am looking for another solution :)
I am also trying to export import with 7zip and will edit on sqlite than will inform you.

**Comment by PredatH0r** [comment] 2023-01-11 21:57
Do you by any chance have a pair of original file + file edited with the online editor saved somewhere?
Comparing the two should give me a clue what the online editor actually changed and what ChanSort is making differently.

Theoretically it's also possible that they broke the import function with a firmware update and then took the site offline.
But I'm not quite ready to give up just yet.

**Comment by PredatH0r** [comment] 2023-01-11 22:07
Have you tried making a minimal change with Chansort, like just swapping program 1 and 2 and upload that file again?
The more complex the changes (like deleting a channel or setting favorites), the more likely it is that the result doesn't meet the TVs expectations.

I uploaded a new build, similar to the one that succeeded for one user, in which only the ProgNum column is updated and nothing else. Maybe you could give that build another try and swap 2 programs:
https://chansort.com/ChanSort_2023-01-11.zip

Thanks,
Horst

**Comment by Gp0n5** [comment] 2023-01-11 22:18
Tried new version and still same. I changed only 1 channel program number.
If you want I can share with you exported and changed tar files.

**Comment by Gp0n5** [comment] 2023-01-11 22:21
[Channel_List_V8-T615T03-LF1V474_2023111.zip](https://github.com/PredatH0r/ChanSort/files/10396345/Channel_List_V8-T615T03-LF1V474_2023111.zip)

**Comment by PredatH0r** [comment] 2023-01-11 22:22
That would be great. The more test files I have, the better.
Could you try to copy the original file from the USB stick to your PC, rename the file on the USB stick and then copy the file back from PC to USB?
It sounds weird, but one user reported that the TV sometimes rejected "unmodified" files just after copying them. I sounds unlikely and something else might have been going on there too. But it's worth testing this out. If that really causes the file to be rejected, it would mean we are at a dead end.

**Comment by PredatH0r** [comment] 2023-01-11 22:41
I think I know now what's going on.
My analysis was based on the file provided by tomxhachijuroku from his P638. That firmware uses CRC16-CCITT for the checksum.
Your TV seems to use a different checksum algorithm. That's why the checksum written by ChanSort is rejected by your model.
I'll try to find out what kind of checksum your TV calculates. Hopefully I can replicate that.

**Comment by PredatH0r** [comment] 2023-01-11 22:57
One last favor: could you export a list from the TV, save the file on the PC. Then move 1 channel with the TVs menu and export that list too.
That should make it easier to find out how the checksum is calculated. Unfortunately it isn't any of the standard candidates.

**Comment by Gp0n5** [comment] 2023-01-11 23:19
[oisorginalcischanged.zip](https://github.com/PredatH0r/ChanSort/files/10396663/oisorginalcischanged.zip)
Channel_List_V8-T615T03-LF1V474_2023111o = Original
Channel_List_V8-T615T03-LF1V474_2023111c = Moved 1 to 3, 3 to 1 from TV.

**Comment by PredatH0r** [comment] 2023-01-11 23:44
Perfect! That did the trick. I was able to crack the CRC mystery with the help of your files.
Looks like the CRC is only calculated over a maximum length of 307200 (0x4B000) bytes, ignoring everything that comes after that. With this limit in place, all TCL files I received so far check out fine.

New build is available at https://chansort.com/ChanSort_2023-01-12.zip
It will now show an error message when opening a list if the cloneCRC.bin contains a checksum that the one calculated by ChanSort.

**Comment by kutyux60** [comment] 2023-01-12 10:59
With this version, you can successfully restore the edited channel list:  ChanSort_2023-01-12
Tested on 43C725 V8-R51MT05-LF1V488 firmware

Thank you very much!

**Comment by matepor464** [comment] 2023-01-12 11:14
> With this version, you can successfully restore the edited channel list: ChanSort_2023-01-12 Tested on 43C725 V8-R51MT05-LF1V488 firmware
> 
> Thank you very much!

So this should also work for me, C635 is the same platform 😁 Will test it after work. The only problem with 2023-01-12 is that deleting channels is disabled, but it is only a minor inconvenience

**Comment by PredatH0r** [comment] 2023-01-12 11:18
Thanks for the feedback!
I'll upload another build a bit later today that allows deleting, setting favorites and skip/lock/hide and shows a couple more columns.
But I could use a few more test files where people send me an original file + then a file where channels were deleted/skipped/locked/hidden/favored through the TV's menu, so I can see what the TV really does.

In the database this information is stored redundantly in the EditFlags and various columns in the AtrributesTbl (yes, that typo is the actual table name in the TV's database). So far I only know the EditFlags bits for Skip and Favorite.

**Comment by matepor464** [comment] 2023-01-12 11:37
I will try to provide these files, hopefully today :)

**Comment by PredatH0r** [comment] 2023-01-12 18:44
Latest build: https://chansort.com/ChanSort_2023-01-12_1925.zip
Changing numbers, setting favorites and "skip" should be save to use.
"lock", "hide" and deleting is still a bit experimental due to lack of sample files with those flags.

**Comment by Gp0n5** [comment] 2023-01-12 19:09
Hello @PredatH0r ,
you can find below sample files.
[2023112_Channel_List_V8-T615T03-LF1V474.zip](https://github.com/PredatH0r/ChanSort/files/10405221/2023112_Channel_List_V8-T615T03-LF1V474.zip)

- Original
- Sorted
- Deleted
- Hided
I didn't see lock option on channel editor on TV

**Comment by PredatH0r** [comment] 2023-01-12 20:36
@Gp0n5 thanks! I made some adjustments based on the findings in your files - and hope now I didn't break anything.
The new version is now an official release: https://github.com/PredatH0r/ChanSort/releases/tag/v2023-01-12

Thanks everyone for your assistance and patience to get this working!

**Comment by Gp0n5** [comment] 2023-01-12 20:42
> @Gp0n5 thanks! I made some adjustments based on the findings in your files - and hope now I didn't break anything. The new version is now an official release: https://github.com/PredatH0r/ChanSort/releases/tag/v2023-01-12
> 
> Thanks everyone for your assistance and patience to get this working!

Worked Perfectly (Y)

**Comment by matepor464** [comment] 2023-01-13 11:57
I confirm, works perfectly. Finally I don't have to scroll past 99999999 FTA channels to get to the ones that I actually watch 😆

**Comment by gcalzo** [comment] 2023-01-13 13:21
> @Gp0n5 thanks! I made some adjustments based on the findings in your files - and hope now I didn't break anything. The new version is now an official release: https://github.com/PredatH0r/ChanSort/releases/tag/v2023-01-12

In the weekend I'll test it on my C715! Thanks for your support!!

**Comment by gcalzo** [comment] 2023-01-14 15:34
> @Gp0n5 thanks! I made some adjustments based on the findings in your files - and hope now I didn't break anything. The new version is now an official release: https://github.com/PredatH0r/ChanSort/releases/tag/v2023-01-12

I confirm that it's working on my TCL C715 (with firmware v6.60, Android TV 9)
1. exported the list to USB
2. opened and just re-saved
3. a file compare showed just a few differences...
4. on the TV I have delete a channel
5. restored the list (BTW, TV always does a **replace** so _deleting a channel_ was probably not needed... :-) )
6. everything is fine and exactly as before the export!! 👍 

I have found two issues:
1. on my TV the channels that you mark _as skipped_ are marked **hided**. Not a big deal but can be confusiong... (in red in the printscreen)
2. the duplicate channes (in green) are actually from different sources: the first is from the **SAT receiver** while the second is from the terrestrial TV. I do not know why the first has the **Satellite** field blank...
![2023-01-14_16-24-33_Window](https://user-images.githubusercontent.com/26879397/212479950-ca980e70-a7ac-4aa6-bd14-85662b233a7d.png)

**Comment by gcalzo** [comment] 2023-01-14 15:48
Fort the second issue above here you are, just in case, my original file exported from TV... 👍 
[Channel_List_V8-R851T02-LF1V660_2023114_org.zip](https://github.com/PredatH0r/ChanSort/files/10418089/Channel_List_V8-R851T02-LF1V660_2023114_org.zip)
BTW: I had to pack the TAR into ZIP for uploading...

**Comment by PredatH0r** [comment] 2023-01-14 16:57
When you select "Hide" on the TV, it actually sets the database column "IsSkipped" to 1. So no matter what I do, either ChanSort's user interface is misleading, or the program code.
But I guess it's better to just have the code be confusing than the UI, so I'll change that.

Also thanks for pointing out the 2nd issue. So far I didn't have any files with more than 1 source. I'll fix that too now.

**Comment by PredatH0r** [comment] 2023-01-14 19:50
New build: https://chansort.com/ChanSort_2023-01-14.zip
- the "Skip" column is gone, its function is now in the "Hide" column.
- separate tabs for DVB-C/T/S lists, which each can start at 1 without conflicts

I'm also no longer loading channels from the database that have the "IsDeleted" flag set. That's why there were 14 DVB-C channels listed in the "File Information" dialog.

(I'll make this an official release once I get feedback about a different issue (Vision Edge 4K receiver) that's also addressed in this build.)

**Closed** 2023-01-22 23:37 UTC
