### ISSUE TITLE
Storing a VDR Chanel list throws exeption

### ISSUE THREAD

**Issue by radiomodell** [PredatH0r/ChanSort#125] opened 2019-01-22 21:01 UTC
Trying to store a VDR .conf file referenced by an other .conf file throws this exeption: 
![fehler](https://user-images.githubusercontent.com/26694127/51564723-58799e00-1e90-11e9-837d-00777572ef46.JPG).
Storing a VDR .conf file referenced with a previounsly saved reference list works fine.
Issue occurs in  ChanSort 2017-11-30 and also in former versions.

**Comment by PredatH0r** [comment] 2019-02-10 16:03
Should be fixed in version 2019-02-10 now.
The problem was caused by the no longer existing channels (shown red in the list).

**Closed by PredatH0r** 2019-02-10 16:03 UTC
