### ISSUE TITLE
Shown frequency is wrong

### ISSUE THREAD

**Issue by McRobber** [PredatH0r/ChanSort#136] opened 2019-07-14 15:42 UTC

**Comment by McRobber** [comment] 2019-07-14 15:50
On frequencylist table every shown frequency shows 200 MHz too high. For example if a frequency of a desired station is in real 498MHz ChanSort shows 696Mhz. I tested it with a Samsung UE55HU8580. The file has the format .scm. The last verison who showed it correct was 2015_04_18. You can use my file for testing, I attached it. Please remove the .txt at the end!
Any help is kindly appreciated.
[channel_list_UE55HU8500_1201.scm.txt](https://github.com/PredatH0r/ChanSort/files/3390121/channel_list_UE55HU8500_1201.scm.txt)

**Comment by PredatH0r** [comment] 2019-07-14 16:03
This is a duplicate of https://github.com/PredatH0r/ChanSort/issues/112

I know that there are SOME files where the frequency is 200Mhz off but there are more files where it is correct.
I have been changing the code back and forth a couple times, but something is always off.
So far I have been unable to find a reliable way to determine the frequency. 

Some .scm files (which are simple .zip files) contain a "PTCAIR" or "PTCCABLE" file that specifies the exact frequencies. When that file is missing, I am using the transponder number and calculate a frequency based of that. My best guess is that it's DVB-T vs. DVB-C transponder numbers and that the frequency differs by 200Mhz between the 2 (assuming the same number).

Maybe I can find a pattern there somewhere.

**Comment by PredatH0r** [comment] 2019-07-14 20:57
It seems indeed to be a DVB-C (106 Mhz) vs. DVB-T (306 Mhz) issue.
This will be fixed in the next update.

**Comment by McRobber** [comment] 2019-07-15 18:03
Dear Horst

 

Thank you for clarification!

 

Best regards

Marcel

 

Von: Horst Beham <notifications@github.com> 
Gesendet: Sonntag, 14. Juli 2019 22:58
An: PredatH0r/ChanSort <ChanSort@noreply.github.com>
Cc: McRobber <m_deplazes@swissonline.ch>; Author <author@noreply.github.com>
Betreff: Re: [PredatH0r/ChanSort] Shown frequency is wrong (#136)

 

It seems indeed to be a DVB-C (106 Mhz) vs. DVB-T (306 Mhz) issue.
This will be fixed in the next update.

**Comment by PredatH0r** [comment] 2019-07-16 10:47
fixed in https://github.com/PredatH0r/ChanSort/releases/tag/v2019-07-16

**Closed** 2019-07-16 10:47 UTC
