### ISSUE TITLE
Edited favourites is not saved

### ISSUE THREAD

**Issue by maherrich** [PredatH0r/ChanSort#11] opened 2015-11-06 16:54 UTC
TV Model: LG 49LF631V-TB
webOS TV Version: 2.2.0-123 (beehive-biscayne)
Software Version: 04.00.30

When I add/remove channels to favorite lists it doesn't save this edited favorites to the channel list file.

**Comment by mootazeg** [comment] 2015-11-21 14:37
Hello, I have same issue here, all changes are not saved
My TV is LG 32LX330C.

Appreciate your advise.

**Comment by PredatH0r** [comment] 2015-11-26 11:52
I can confirm the issue with Favorites for the LF series and others which use the GlobalClone file format. This will be fixed in v2015-11-26 (to be released later today).

For the LX series I only have a single test file, and that only contains Cable-TV channels.
To support other channel types (satellite, antenna) I need a sample file to analyze the format. Unfortunately LG pretty much uses a different format for every model.

**Comment by mootazeg** [comment] 2015-11-27 16:35
Hello. thanks for your care and support, you can find attached sample file for LX330c DVB-S2 model from LG, i did sent it via email earlier, wish it could be helpful. i had to change the extension to upload, please rename the extension to .TLL. Thanks again.
![globalclone00001](https://cloud.githubusercontent.com/assets/15955868/11445508/3f1dc8ba-9535-11e5-8795-1bd4f465431e.png)

**Comment by mootazeg** [comment] 2015-11-27 16:47
Thanks Horst for your prompt and personal response, really appreciated.
Please find attached copy of the LG LX file (Satellite - DVB-S2) obtained
from 32LX330c Model, wish it could be helpful.

Regards,

Mootaz

**Comment by mootazeg** [comment] 2015-11-27 16:50
Hi Horst,

got some good news, i have just started testing the newest version you
developed (27-11), and it seems to be working, the favorit have been saved
to the file, remaining to upload the file to the TV and find out how it
goes, will surely keep you posted, thanks my friend.

Regards,

Mootaz

**Closed** 2015-11-29 11:29 UTC
